DROP TABLE IF EXISTS TIME_EXTEND CASCADE;
DROP TABLE IF EXISTS SONG_ACTIVITIES CASCADE;
DROP TABLE IF EXISTS SONGS CASCADE;
DROP TABLE IF EXISTS ROOM CASCADE;
DROP TABLE IF EXISTS RESERVATION CASCADE;
DROP TABLE IF EXISTS REGISTRATION CASCADE;
DROP TABLE IF EXISTS PICK CASCADE;
DROP TABLE IF EXISTS PAYMENT CASCADE;
DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    NO_PHONE VARCHAR(13),
    NAME VARCHAR(80),
    PEOPLE_COMING INT
);

CREATE TABLE MEMBER (
    CUSTOMER_ID INT PRIMARY KEY,
    MEMBER_STATUS VARCHAR(9),
    NUMBER_OF_VISITS INT,
    DISCOUNT_MEMBER FLOAT8
);

CREATE TABLE PAYMENT (
    PAYMENT_ID SERIAL PRIMARY KEY,
    PAYMENT_TIME TIMESTAMP,
    PAYMENT_METHOD VARCHAR(10),
    TOTAL_COST NUMERIC(8,2),
    DISCOUNT_MEMBER FLOAT8,
    FINAL_COST NUMERIC(8,2)
);

CREATE TABLE SONGS (
    SONGS_ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(250),
    ARTIST VARCHAR(80),
    GENRE VARCHAR(25),
    LANGUAGE VARCHAR(25),
    DURATION TIME,
    LYRICS TEXT
);

CREATE TABLE SONG_ACTIVITIES (
    ACTIVITY_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    SONG_START_TIME TIMESTAMP,
    PLAYED_DURATION TIME,
    PLAYED_PERCENTAGE FLOAT8
);

CREATE TABLE PICK (
    SONGS_ID INT NOT NULL,
    ACTIVITY_ID INT NOT NULL
);

CREATE TABLE REGISTRATION (
    ID_TRANSAKSI2 SERIAL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_ID INT NOT NULL,
    DATE DATE,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    REGISTRATION_STATUS VARCHAR(20)
);

CREATE TABLE RESERVATION (
    RESERVATION_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_ID INT NOT NULL,
    DATE DATE,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    RESERVATION_DATE DATE,
    PCT_DP FLOAT8,
    PAID_DP NUMERIC(8,2),
    LATE BOOLEAN
);

CREATE TABLE ROOM (
    ROOM_ID SERIAL PRIMARY KEY,
    ID_TRANSAKSI2 INT,
    RESERVATION_ID INT,
    ROOM_TYPE VARCHAR(10),
    CAPACITY INT,
    HOURLY_RATE NUMERIC(8,2),
    STATUS VARCHAR(20)
);

CREATE TABLE TIME_EXTEND (
    EXTEND_ID SERIAL PRIMARY KEY,
    ID_TRANSAKSI2 INT,
    RESERVATION_ID INT,
    EXTENSION_DURATION TIME,
    EXTENSION_COST NUMERIC(8,2)
);

ALTER TABLE MEMBER
ADD CONSTRAINT FK_MEMBER_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID)
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SONG_ACTIVITIES
ADD CONSTRAINT FK_SONG_ACT_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID)
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PICK
ADD CONSTRAINT FK_PICK_SONG
FOREIGN KEY (SONGS_ID)
REFERENCES SONGS(SONGS_ID);

ALTER TABLE PICK
ADD CONSTRAINT FK_PICK_ACTIVITY
FOREIGN KEY (ACTIVITY_ID)
REFERENCES SONG_ACTIVITIES(ACTIVITY_ID);

ALTER TABLE REGISTRATION
ADD CONSTRAINT FK_REG_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE REGISTRATION
ADD CONSTRAINT FK_REG_PAYMENT
FOREIGN KEY (PAYMENT_ID)
REFERENCES PAYMENT(PAYMENT_ID);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RES_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RES_PAYMENT
FOREIGN KEY (PAYMENT_ID)
REFERENCES PAYMENT(PAYMENT_ID);

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_REGISTRATION
FOREIGN KEY (ID_TRANSAKSI2)
REFERENCES REGISTRATION(ID_TRANSAKSI2);

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_RESERVATION
FOREIGN KEY (RESERVATION_ID)
REFERENCES RESERVATION(RESERVATION_ID);

ALTER TABLE TIME_EXTEND
ADD CONSTRAINT FK_EXTEND_REG
FOREIGN KEY (ID_TRANSAKSI2)
REFERENCES REGISTRATION(ID_TRANSAKSI2);

ALTER TABLE TIME_EXTEND
ADD CONSTRAINT FK_EXTEND_RES
FOREIGN KEY (RESERVATION_ID)
REFERENCES RESERVATION(RESERVATION_ID);
